Revert "add new fiddle security wrapper"
Undoing bad approach to fiddle security; this should take us back far enough that we can still give
demos.

This reverts commit 157e0e3484a6d54a43eb27ef11ee34cf1ddc073b.

BUG=skia:3515

Review URL: https://codereview.chromium.org/1063463003

diff --git a/webtry/scripts/fiddle_run b/webtry/scripts/fiddle_run
--- a/webtry/scripts/fiddle_run
+++ b/webtry/scripts/fiddle_run
@@ -8,10 +8,12 @@
 [ -z $SKIA_ROOT ] && SKIA_ROOT="/skia_build/skia"
 [ -z $WEBTRY_INOUT ] && WEBTRY_INOUT="/skia_build/inout"
 
-if [ "$(uname)" == "Linux" ]; then
-	EXECUTABLE="$SKIA_ROOT/out/Release_Developer/fiddle_secwrap $SKIA_ROOT/out/Release_Developer/$1"
-else
-	EXECUTABLE="$SKIA_ROOT/out/Release_Developer/$1"
+EXECUTABLE=$SKIA_ROOT/out/Release_Developer/$1
+OBJ=$SKIA_ROOT/out/Release_Developer/cache/src/$1.$1.o
+
+if nm $OBJ | grep " T " | grep -v -q "_Z4drawP8SkCanvas$"; then
+	echo "Could not run your fiddle."
+	exit 1
 fi
 
 echo "-=-=-=-=-=-=-"
